# Generated by Django 4.1.4 on 2022-12-20 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=300, null=True)),
                ('Sub_heading', models.CharField(blank=True, max_length=300, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Blog_Image', models.ImageField(blank=True, null=True, upload_to='files/BlogImages')),
                ('Street', models.CharField(blank=True, max_length=300, null=True)),
                ('Suburb', models.CharField(blank=True, max_length=300, null=True)),
                ('City_Town', models.CharField(blank=True, max_length=300, null=True)),
                ('Province', models.CharField(blank=True, max_length=300, null=True)),
                ('Event_TimeStart', models.CharField(blank=True, max_length=300, null=True)),
                ('Event_TimeEnd', models.CharField(blank=True, max_length=300, null=True)),
                ('Event_Startdate', models.DateField(blank=True, null=True)),
                ('Event_EndDate', models.DateField(blank=True, null=True)),
                ('LinkOne', models.CharField(blank=True, max_length=1000, null=True)),
                ('LinkTwo', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(blank=True, max_length=300, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Sub_Total', models.FloatField(blank=True, null=True)),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('satus', models.CharField(choices=[('cart', 'cart'), ('pending', 'pending'), ('paid', 'paid'), ('complete', 'complete')], default='cart', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, null=True)),
                ('Category_Image', models.ImageField(blank=True, null=True, upload_to='files/CategoryImages')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, null=True)),
                ('Hex', models.CharField(max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('formComplete', models.CharField(blank=True, default='No', max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=300, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LayByOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Yes', max_length=100, null=True)),
                ('Monthsdata', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaxiPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bag', models.CharField(blank=True, max_length=300, null=True)),
                ('size', models.CharField(blank=True, max_length=300, null=True)),
                ('days', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('ReStock_Level', models.IntegerField(blank=True, null=True)),
                ('main_Image', models.ImageField(blank=True, null=True, upload_to='files/ProductImages')),
                ('Image_One', models.ImageField(blank=True, null=True, upload_to='files/ProductImages')),
                ('Image_Two', models.ImageField(blank=True, null=True, upload_to='files/ProductImages')),
                ('Image_Three', models.ImageField(blank=True, null=True, upload_to='files/ProductImages')),
                ('main_display', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True)),
                ('sale', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True)),
                ('Sale_Price', models.FloatField(blank=True, null=True)),
                ('End_date', models.DateField(blank=True, null=True)),
                ('sale_CoverImages', models.CharField(blank=True, choices=[('First', 'First'), ('second', 'second'), ('third', 'third')], default='No', max_length=10, null=True)),
                ('new', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True)),
                ('arrivals_CoverImages', models.CharField(blank=True, choices=[('First', 'First'), ('second', 'second'), ('third', 'third')], default='No', max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Category', models.ManyToManyField(blank=True, default=None, related_name='product_Category', to='client.category')),
                ('Colors', models.ManyToManyField(blank=True, default=None, related_name='product_Colors', to='client.colours')),
                ('Sizes', models.ManyToManyField(blank=True, default=None, related_name='product_Sizes', to='client.itemsize')),
                ('layby', models.ManyToManyField(blank=True, default=None, related_name='layBy_options', to='client.laybyoptions')),
            ],
        ),
        migrations.CreateModel(
            name='SaleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_Price', models.FloatField(blank=True, null=True)),
                ('End_date', models.DateField(blank=True, null=True)),
                ('main_display', models.CharField(choices=[('First', 'First'), ('second', 'second'), ('third', 'third')], default='No', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sale_collection', to='client.product')),
            ],
        ),
        migrations.CreateModel(
            name='NewArrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_Price', models.FloatField(blank=True, null=True)),
                ('End_date', models.DateField(blank=True, null=True)),
                ('main_display', models.CharField(choices=[('First', 'First'), ('second', 'second'), ('third', 'third')], default='No', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='new_arrivals', to='client.product')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Option_Picked', models.CharField(blank=True, max_length=100, null=True)),
                ('GrandTotal', models.FloatField(blank=True, null=True)),
                ('AmountDue', models.FloatField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
                ('LastName', models.CharField(blank=True, max_length=300, null=True)),
                ('Contact', models.CharField(blank=True, max_length=300, null=True)),
                ('AltContact', models.CharField(blank=True, max_length=300, null=True)),
                ('Email', models.CharField(blank=True, max_length=300, null=True)),
                ('ComplexDetails', models.CharField(blank=True, max_length=300, null=True)),
                ('Street', models.CharField(blank=True, max_length=300, null=True)),
                ('Suburb', models.CharField(blank=True, max_length=300, null=True)),
                ('City', models.CharField(blank=True, max_length=300, null=True)),
                ('Province', models.CharField(blank=True, max_length=300, null=True)),
                ('PostalCode', models.CharField(blank=True, max_length=300, null=True)),
                ('object_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_ref', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paxiPackageId', models.CharField(blank=True, max_length=100, null=True)),
                ('deliveryFee', models.FloatField(blank=True, null=True)),
                ('addressLine1', models.CharField(blank=True, max_length=300, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=300, null=True)),
                ('addressLine3', models.CharField(blank=True, max_length=300, null=True)),
                ('addressLine4', models.CharField(blank=True, max_length=300, null=True)),
                ('addressLine5', models.CharField(blank=True, max_length=300, null=True)),
                ('addressLine6', models.CharField(blank=True, max_length=300, null=True)),
                ('addressLine7', models.CharField(blank=True, max_length=300, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('CustomerId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='client.customermodel')),
                ('UserItems', models.ManyToManyField(blank=True, default=None, related_name='user_cart', to='client.cartitems')),
            ],
        ),
        migrations.AddField(
            model_name='cartitems',
            name='CustomerId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_cart', to='client.customermodel'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='ProductKey',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_key', to='client.product'),
        ),
    ]
